### ISSUE TITLE
`sslutils` cannot be used in the presence of environment variables that contain Unicode

### ISSUE THREAD

**Issue by jugglinmike** [w3c/wpt-tools#163]
In gh-139, the `sslutils` module was updated to account for an encoding issue
in Windows. This change causes errors when a variable contains a Unicode code
point.

The following log from the continuous integration system for the
`web-platform-tests` project demonstrates the problem:

    Traceback (most recent call last):
      File "check_stability.py", line 752, in <module>
        retcode = main()
      File "check_stability.py", line 731, in main
        wptrunner.run_tests(**kwargs)
      File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/wptrunner.py", line 156, in run_tests
        env_options) as test_environment:
      File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/environment.py", line 106, in __enter__
        self.config = self.load_config()
      File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/environment.py", line 154, in load_config
        key_file, certificate = self.ssl_env.host_cert_path(hosts)
      File "/home/travis/build/w3c/web-platform-tests/tools/sslutils/openssl.py", line 360, in host_cert_path
        key, cert = self._generate_host_cert(hosts)
      File "/home/travis/build/w3c/web-platform-tests/tools/sslutils/openssl.py", line 380, in _generate_host_cert
        self._generate_ca()
      File "/home/travis/build/w3c/web-platform-tests/tools/sslutils/openssl.py", line 331, in _generate_ca
        "-passout", "pass:%s" % self.password)
      File "/home/travis/build/w3c/web-platform-tests/tools/sslutils/openssl.py", line 65, in __call__
        env[k.encode("utf8")] = v.encode("utf8")

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

(see https://github.com/w3c/web-platform-tests/pull/4771)

In this case, the system was running `wptrunner` for a build whose git branch
was named with a Unicode code point, and the CI is configured to include branch
information in the environment.

I have not been able to reproduce the original issue locally (using Windows 7,
MSysgit, and Python 2.7.11), so I am not comfortable submitting a patch.
@metajack: could you share which version of Windows was exhibiting this
problem?

**Comment by gsnedders** [comment]
Uh, if we're getting a UnicodeDecodeError that implies that one of `k` and `v` is already a `str` object, and is being implicitly decoded for the call to `encode`.

**Comment by metajack** [comment]
In case it matters, it was Windows 10 and (windows) Python 2.7.11.

**Comment by lyzadanger** [comment]
I've encountered a related error as well, on a Mac, when trying to run the `./serve` script for [web-platform-tests](https://github.com/w3c/web-platform-tests) (Mac OS 10.11.6, python 2.7.13):

```
$ ./serve
DEBUG:web-platform-tests:Going to use port 65173
DEBUG:web-platform-tests:Going to use port 65174
DEBUG:web-platform-tests:Going to use port 65175
DEBUG:web-platform-tests:Going to use port 65176
INFO:web-platform-tests:Generating new CA in /Users/lyza/Projects/web-platform-tests/_certs
Traceback (most recent call last):
  File "./serve", line 5, in <module>
    serve.main()
  File "/Users/lyza/Projects/web-platform-tests/serve.py", line 12, in main
    serve.main()
  File "/Users/lyza/Projects/web-platform-tests/tools/serve/serve.py", line 660, in main
    config_, servers = start(config, ssl_env, build_routes(config["aliases"]), **kwargs)
  File "/Users/lyza/Projects/web-platform-tests/tools/serve/serve.py", line 534, in start
    ssl_config = get_ssl_config(config, external_config["domains"].values(), ssl_environment)
  File "/Users/lyza/Projects/web-platform-tests/tools/serve/serve.py", line 518, in get_ssl_config
    key_path, cert_path = ssl_environment.host_cert_path(external_domains)
  File "/Users/lyza/Projects/web-platform-tests/tools/sslutils/openssl.py", line 368, in host_cert_path
    key, cert = self._generate_host_cert(hosts)
  File "/Users/lyza/Projects/web-platform-tests/tools/sslutils/openssl.py", line 388, in _generate_host_cert
    self._generate_ca()
  File "/Users/lyza/Projects/web-platform-tests/tools/sslutils/openssl.py", line 339, in _generate_ca
    "-passout", "pass:%s" % self.password)
  File "/Users/lyza/Projects/web-platform-tests/tools/sslutils/openssl.py", line 70, in __call__
    env[k.encode("utf8")] = v.encode("utf8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 15: ordinal not in range(128)
```
